# Default values for MySql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
mysql:

  name: mysql 

  nameSpace: helm-2-tier-app

  replicaCount: 2

  image:
    repository: mysql:5.7
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
  service:
    port: 3306

  seCret:
    naMe: MYSQL_ROOT_PASSWORD
    kEy: ROOT_PASSWORD   

  dataBases: 
    naMe: MYSQL_DATABASE
    dataBase: todos
    kEy: MYSQL_DATABASE

myadmin:

  name: myadmin   

  nameSpace: helm-2-tier-app

  replicaCount: 2

  image:
    repository: phpmyadmin/phpmyadmin
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion. 

  enVs:
    connectKey: PMA_HOST
    connectValue: mysql-headless-svc.helm-2-tier-app.svc.cluster.local
    portKey: PMA_PORT
    portValue: 3306

  



    





